apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  namespace: business-app
spec:
  containers:
  - name: container
    image: {PLACEHOLDER_KALI_REPO_URL}
    imagePullPolicy: IfNotPresent
    command: [ "/bin/sh", "-c", "--" ]
    args: [ "apt-get update; apt-get install -y curl iproute2 nmap; while true; do sleep 30; done;" ]
